-- Add admins table to Supabase
-- Run this in your Supabase SQL Editor

-- Add admins table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read on admins" ON admins FOR SELECT USING (true);
CREATE POLICY "Allow public write on admins" ON admins FOR ALL USING (true);

-- Add to realtime
DO $$
BEGIN
  EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE admins';
EXCEPTION
  WHEN duplicate_object THEN
    RAISE NOTICE 'Table admins is already in publication supabase_realtime';
END
$$;

-- Create updated_at trigger for admins
DROP TRIGGER IF EXISTS update_admins_updated_at ON admins;
CREATE TRIGGER update_admins_updated_at
BEFORE UPDATE ON admins
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create increment version trigger for admins
DROP TRIGGER IF EXISTS increment_version_admins ON admins;
CREATE TRIGGER increment_version_admins
AFTER INSERT OR UPDATE OR DELETE ON admins
FOR EACH STATEMENT EXECUTE FUNCTION increment_global_version();

-- Insert initial admin user if not exists
INSERT INTO admins (username, password)
SELECT 'admin', 'admin'
WHERE NOT EXISTS (SELECT 1 FROM admins WHERE username = 'admin');
