const fs = require('fs');
const path = require('path');

console.log("Build step started...");

// Generate supabase-config.js from environment variables
const config = `// Auto-generated by build.js
window.SUPABASE_URL = "${process.env.SUPABASE_URL || ''}";
window.SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY || ''}";
window.SUPABASE_BUCKET = "${process.env.SUPABASE_BUCKET || ''}";
`;

const configPath = path.join(__dirname, 'supabase-config.js');
fs.writeFileSync(configPath, config);
console.log("Generated supabase-config.js successfully!");
console.log("Build step completed.");
