services:
  - type: web
    name: hov-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
