-- Supabase Setup Script for House of Viyara
-- Run this in your Supabase SQL Editor

-- Drop existing tables to ensure clean setup (optional, remove if you want to keep data)
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS banners;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS header_links;
DROP TABLE IF EXISTS hero_images;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create products table with proper defaults
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    description TEXT,
    price NUMERIC,
    offer_price NUMERIC,
    category TEXT,
    image_url TEXT,
    video_url TEXT,
    gallery TEXT[] DEFAULT '{}',
    videos TEXT[] DEFAULT '{}',
    stock INTEGER DEFAULT 10,
    rating NUMERIC DEFAULT 4.5,
    is_trending BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon TEXT DEFAULT 'fas fa-tag',
    banner_image TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create banners table
CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subtitle TEXT,
    image_url TEXT,
    cta_text TEXT DEFAULT 'Shop Now',
    cta_link TEXT DEFAULT 'collections.html',
    is_active BOOLEAN DEFAULT true NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create orders table
CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    items JSONB,
    total_amount NUMERIC,
    status TEXT DEFAULT 'Pending',
    shipping_address JSONB,
    txnid TEXT,
    payment_status TEXT DEFAULT 'Unpaid',
    payu_response JSONB,
    payment_gateway TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create header links table
CREATE TABLE header_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    href TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create hero images table
CREATE TABLE hero_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT,
    alt TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true NOT NULL,
    duration INTEGER DEFAULT 3000, -- in milliseconds
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE header_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_images ENABLE ROW LEVEL SECURITY;

-- Create public access policies
CREATE POLICY "Allow public read on products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public write on products" ON products FOR ALL USING (true);

CREATE POLICY "Allow public read on categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public write on categories" ON categories FOR ALL USING (true);

CREATE POLICY "Allow public read on banners" ON banners FOR SELECT USING (true);
CREATE POLICY "Allow public write on banners" ON banners FOR ALL USING (true);

CREATE POLICY "Allow public read on orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public write on orders" ON orders FOR ALL USING (true);

CREATE POLICY "Allow public read on header_links" ON header_links FOR SELECT USING (true);
CREATE POLICY "Allow public write on header_links" ON header_links FOR ALL USING (true);

CREATE POLICY "Allow public read on hero_images" ON hero_images FOR SELECT USING (true);
CREATE POLICY "Allow public write on hero_images" ON hero_images FOR ALL USING (true);

-- Enable Realtime for all tables
alter publication supabase_realtime add table products;
alter publication supabase_realtime add table categories;
alter publication supabase_realtime add table banners;
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table header_links;
alter publication supabase_realtime add table hero_images;

-- Insert sample data (10 products)
INSERT INTO products (name, description, price, offer_price, category, image_url, video_url, is_trending)
SELECT 'Floral Maxi Dress', 'Elegant floor-length maxi with delicate floral print.', 4500, 3999, 'maxis', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80', NULL, true
WHERE NOT EXISTS (SELECT 1 FROM products LIMIT 1);

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Satin Evening Maxi', 'Luxurious satin maxi perfect for special occasions.', 6200, 'maxis', 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 2;

INSERT INTO products (name, description, price, offer_price, category, image_url, is_trending)
SELECT 'Cord Set - Pastel', 'Comfortable two-piece cord set in soft pastel colors.', 1299, 999, 'cord-sets', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 3;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Chikankari Cotton Kurti', 'Handcrafted Lucknowi chikankari embroidery on soft cotton.', 2499, 'kurti', 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=800&q=80', true
WHERE (SELECT COUNT(*) FROM products) < 4;

INSERT INTO products (name, description, price, category, image_url, video_url, is_trending)
SELECT 'Kurti Set with Dupatta', 'Complete kurti set with matching dupatta and bottoms.', 4500, 'kurti-sets', 'https://images.unsplash.com/photo-1613376023733-0a7331569763?w=800&q=80', 'https://www.w3schools.com/html/mov_bbb.mp4', true
WHERE (SELECT COUNT(*) FROM products) < 5;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'A-Line Rayon Kurti', 'Comfortable straight-cut daily wear rayon kurti.', 1899, 'kurti', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 6;

INSERT INTO products (name, description, price, offer_price, category, image_url, video_url, is_trending)
SELECT 'Bohemian Maxi', 'Free-spirited bohemian style maxi dress.', 3500, 2999, 'maxis', 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80', 'https://www.w3schools.com/html/movie.mp4', true
WHERE (SELECT COUNT(*) FROM products) < 7;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Cord Set - Printed', 'Trendy printed cord set for casual outings.', 1999, 'cord-sets', 'https://images.unsplash.com/photo-1515372039744-b8f02a3434b8?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 8;

INSERT INTO products (name, description, price, offer_price, category, image_url, is_trending)
SELECT 'Party Wear Kurti Set', 'Glitzy kurti set perfect for parties and celebrations.', 5200, 4499, 'kurti-sets', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 9;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Pastel Georgette Kurti', 'Elegant long kurti with bell sleeves and side slit.', 1600, 'kurti', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 10;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Maxis', 'maxis', 'fas fa-female', 1
WHERE NOT EXISTS (SELECT 1 FROM categories LIMIT 1);

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Cord sets', 'cord-sets', 'fas fa-tshirt', 2
WHERE (SELECT COUNT(*) FROM categories) < 2;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Kurti', 'kurti', 'fas fa-star', 3
WHERE (SELECT COUNT(*) FROM categories) < 3;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Kurti sets', 'kurti-sets', 'fas fa-glass-cheers', 4
WHERE (SELECT COUNT(*) FROM categories) < 4;

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Maxis Collection', 'Elegant maxi dresses for every occasion', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=80', 'Maxis.html', 'Explore Maxis', true, 1
WHERE NOT EXISTS (SELECT 1 FROM banners LIMIT 1);

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Kurti Collection', 'Soft prints and rich embroidery for daily wear', 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=1200&q=80', 'Kurti.html', 'Shop Kurtis', true, 2
WHERE (SELECT COUNT(*) FROM banners) < 2;

-- Insert sample header links
INSERT INTO header_links (name, slug, href, display_order, is_active)
SELECT 'Maxis', 'maxis', 'Maxis.html', 1, true
WHERE NOT EXISTS (SELECT 1 FROM header_links LIMIT 1);

INSERT INTO header_links (name, slug, href, display_order, is_active)
SELECT 'Cord sets', 'cord-sets', 'Cord sets.html', 2, true
WHERE (SELECT COUNT(*) FROM header_links) < 2;

INSERT INTO header_links (name, slug, href, display_order, is_active)
SELECT 'Kurti', 'kurti', 'Kurti.html', 3, true
WHERE (SELECT COUNT(*) FROM header_links) < 3;

INSERT INTO header_links (name, slug, href, display_order, is_active)
SELECT 'Kurti sets', 'kurti-sets', 'Kurti sets.html', 4, true
WHERE (SELECT COUNT(*) FROM header_links) < 4;

-- Insert sample hero images
INSERT INTO hero_images (image_url, alt, display_order, is_active, duration)
SELECT 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=80', 'Premium Saree Collection', 1, true, 3000
WHERE NOT EXISTS (SELECT 1 FROM hero_images LIMIT 1);

INSERT INTO hero_images (image_url, alt, display_order, is_active, duration)
SELECT 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=1200&q=80', 'Kurti Collection', 2, true, 3000
WHERE (SELECT COUNT(*) FROM hero_images) < 2;

INSERT INTO hero_images (image_url, alt, display_order, is_active, duration)
SELECT 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1200&q=80', 'Party Wear Gowns', 3, true, 3000
WHERE (SELECT COUNT(*) FROM hero_images) < 3;
