-- Supabase Setup Script for House of Viyara
-- Run this in your Supabase SQL Editor

-- Drop existing tables to ensure clean setup (optional, remove if you want to keep data)
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS banners;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create products table with proper defaults
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    description TEXT,
    price NUMERIC,
    offer_price NUMERIC,
    category TEXT,
    image_url TEXT,
    video_url TEXT,
    stock INTEGER DEFAULT 10,
    rating NUMERIC DEFAULT 4.5,
    is_trending BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon TEXT DEFAULT 'fas fa-tag',
    banner_image TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create banners table
CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subtitle TEXT,
    image_url TEXT NOT NULL,
    cta_text TEXT DEFAULT 'Shop Now',
    cta_link TEXT DEFAULT 'collections.html',
    is_active BOOLEAN DEFAULT true NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create orders table
CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    items JSONB,
    total_amount NUMERIC,
    status TEXT DEFAULT 'Pending',
    shipping_address JSONB,
    txnid TEXT,
    payment_status TEXT DEFAULT 'Unpaid',
    payu_response JSONB,
    payment_gateway TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create public access policies
CREATE POLICY "Allow public read on products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public write on products" ON products FOR ALL USING (true);

CREATE POLICY "Allow public read on categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public write on categories" ON categories FOR ALL USING (true);

CREATE POLICY "Allow public read on banners" ON banners FOR SELECT USING (true);
CREATE POLICY "Allow public write on banners" ON banners FOR ALL USING (true);

CREATE POLICY "Allow public read on orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public write on orders" ON orders FOR ALL USING (true);

-- Insert sample data
INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Banarasi Silk Saree', 'Elegant gold zari border with premium silk fabric.', 4500, 'saree', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80', true
WHERE NOT EXISTS (SELECT 1 FROM products LIMIT 1);

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Kanjeevaram Saree', 'Pure mulberry silk with traditional temple patterns.', 6200, 'saree', 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 2;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Saree', 'saree', 'fas fa-female', 1
WHERE NOT EXISTS (SELECT 1 FROM categories LIMIT 1);

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Kurtis', 'kurtis', 'fas fa-tshirt', 2
WHERE (SELECT COUNT(*) FROM categories) < 2;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Ethnic Wear', 'ethnic', 'fas fa-star', 3
WHERE (SELECT COUNT(*) FROM categories) < 3;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Party Wear', 'party', 'fas fa-glass-cheers', 4
WHERE (SELECT COUNT(*) FROM categories) < 4;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Casual Wear', 'casual', 'fas fa-leaf', 5
WHERE (SELECT COUNT(*) FROM categories) < 5;

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Saree Spotlight', 'Handpicked premium sarees for every occasion', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=80', 'saree.html', 'Explore Sarees', true, 1
WHERE NOT EXISTS (SELECT 1 FROM banners LIMIT 1);

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Kurtis Collection', 'Soft prints and rich embroidery for daily wear', 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=1200&q=80', 'kurtis.html', 'Shop Kurtis', true, 2
WHERE (SELECT COUNT(*) FROM banners) < 2;
