-- Supabase Setup Script for House of Viyara
-- Run this in your Supabase SQL Editor

-- Drop existing tables to ensure clean setup (optional, remove if you want to keep data)
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS banners;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create products table with proper defaults
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    description TEXT,
    price NUMERIC,
    offer_price NUMERIC,
    category TEXT,
    image_url TEXT,
    video_url TEXT,
    gallery TEXT[] DEFAULT '{}',
    videos TEXT[] DEFAULT '{}',
    stock INTEGER DEFAULT 10,
    rating NUMERIC DEFAULT 4.5,
    is_trending BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon TEXT DEFAULT 'fas fa-tag',
    banner_image TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create banners table
CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subtitle TEXT,
    image_url TEXT NOT NULL,
    cta_text TEXT DEFAULT 'Shop Now',
    cta_link TEXT DEFAULT 'collections.html',
    is_active BOOLEAN DEFAULT true NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create orders table
CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    items JSONB,
    total_amount NUMERIC,
    status TEXT DEFAULT 'Pending',
    shipping_address JSONB,
    txnid TEXT,
    payment_status TEXT DEFAULT 'Unpaid',
    payu_response JSONB,
    payment_gateway TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create public access policies
CREATE POLICY "Allow public read on products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public write on products" ON products FOR ALL USING (true);

CREATE POLICY "Allow public read on categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public write on categories" ON categories FOR ALL USING (true);

CREATE POLICY "Allow public read on banners" ON banners FOR SELECT USING (true);
CREATE POLICY "Allow public write on banners" ON banners FOR ALL USING (true);

CREATE POLICY "Allow public read on orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public write on orders" ON orders FOR ALL USING (true);

-- Enable Realtime for all tables
alter publication supabase_realtime add table products;
alter publication supabase_realtime add table categories;
alter publication supabase_realtime add table banners;
alter publication supabase_realtime add table orders;

-- Insert sample data (10 products)
INSERT INTO products (name, description, price, offer_price, category, image_url, video_url, is_trending)
SELECT 'Banarasi Silk Saree', 'Elegant gold zari border with premium silk fabric.', 4500, 3999, 'saree', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80', NULL, true
WHERE NOT EXISTS (SELECT 1 FROM products LIMIT 1);

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Kanjeevaram Saree', 'Pure mulberry silk with traditional temple patterns.', 6200, 'saree', 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 2;

INSERT INTO products (name, description, price, offer_price, category, image_url, is_trending)
SELECT 'Floral Print Kurti', 'Soft cotton with vibrant floral prints.', 1299, 999, 'kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 3;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Embroidered Kurti Set', 'Heavy thread work kurti with dupatta.', 2499, 'kurtis', 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=800&q=80', true
WHERE (SELECT COUNT(*) FROM products) < 4;

INSERT INTO products (name, description, price, category, image_url, video_url, is_trending)
SELECT 'Lehenga Choli Set', 'Bridal lehenga with intricate embroidery.', 15999, 'ethnic', 'https://images.unsplash.com/photo-1613376023733-0a7331569763?w=800&q=80', 'https://www.w3schools.com/html/mov_bbb.mp4', true
WHERE (SELECT COUNT(*) FROM products) < 5;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Salwar Kameez', 'Comfortable cotton salwar suit.', 1899, 'ethnic', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 6;

INSERT INTO products (name, description, price, offer_price, category, image_url, video_url, is_trending)
SELECT 'Party Wear Gown', 'Sequined evening gown for special occasions.', 7999, 6499, 'party', 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80', 'https://www.w3schools.com/html/movie.mp4', true
WHERE (SELECT COUNT(*) FROM products) < 7;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Cocktail Dress', 'Satin cocktail dress in deep red.', 4999, 'party', 'https://images.unsplash.com/photo-1515372039744-b8f02a3434b8?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 8;

INSERT INTO products (name, description, price, offer_price, category, image_url, is_trending)
SELECT 'Casual T-Shirt', 'Soft cotton t-shirt for daily wear.', 599, 399, 'casual', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 9;

INSERT INTO products (name, description, price, category, image_url, is_trending)
SELECT 'Denim Jeans', 'Comfort-fit blue denim jeans.', 1499, 'casual', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80', false
WHERE (SELECT COUNT(*) FROM products) < 10;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Saree', 'saree', 'fas fa-female', 1
WHERE NOT EXISTS (SELECT 1 FROM categories LIMIT 1);

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Kurtis', 'kurtis', 'fas fa-tshirt', 2
WHERE (SELECT COUNT(*) FROM categories) < 2;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Ethnic Wear', 'ethnic', 'fas fa-star', 3
WHERE (SELECT COUNT(*) FROM categories) < 3;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Party Wear', 'party', 'fas fa-glass-cheers', 4
WHERE (SELECT COUNT(*) FROM categories) < 4;

INSERT INTO categories (name, slug, icon, display_order)
SELECT 'Casual Wear', 'casual', 'fas fa-leaf', 5
WHERE (SELECT COUNT(*) FROM categories) < 5;

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Saree Spotlight', 'Handpicked premium sarees for every occasion', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=80', 'saree.html', 'Explore Sarees', true, 1
WHERE NOT EXISTS (SELECT 1 FROM banners LIMIT 1);

INSERT INTO banners (title, subtitle, image_url, cta_link, cta_text, is_active, display_order)
SELECT 'Kurtis Collection', 'Soft prints and rich embroidery for daily wear', 'https://images.unsplash.com/photo-1608748010899-18f300247112?w=1200&q=80', 'kurtis.html', 'Shop Kurtis', true, 2
WHERE (SELECT COUNT(*) FROM banners) < 2;
